### ISSUE TITLE
Migrate Environment & Urbanization site

### ISSUE THREAD

**Issue by cbrody** [IIED-org/eandu#20]
www.environmentandurbanization.org
https://prod.environmentandurbanization.org

- [x] Test prod site
- [x] Migrate code & config
- [x] Set TTLs to 5 mins
- [x] Content freeze - readonlymode?
- [x] Migrate db & files
- [x] Test
- [x] Update DNS etc.
- [x] Test

Launch target: 20241022T10:00

**Comment by stephen-cox** [comment]
@cbrody The E & U site is setup on the new server and ready for testing here: https://prod.environmentandurbanization.org/

Let me know if you find anything that's not working as expected.
